apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.image.repository }}/backend-service:{{ .Values.image.backendTag }}"
        ports:
        - containerPort: {{ .Values.backend.containerPort }}
      imagePullSecrets:
      - name: ecr-pull-secret
